name: Tests
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  lint:
    name: Lint with PHP_CodeSniffer
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install composer dependencies
        run: composer install
      - name: Lint with PHP_CodeSniffer
        run: vendor/bin/phpcs
  tests:
    name: Test with PHPUnit
    strategy:
      fail-fast: false
      matrix:
        bench:
          - laravel-5.8
          - laravel-6.0
          - laravel-7.0
          - laravel-8.0
          - lumen-5.8
          - lumen-6.0
          - lumen-7.0
          - lumen-8.0
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0' ]
        exclude:
          - bench: laravel-5.8
            php: '8.0'
          - bench: laravel-6.0
            php: '7.1'
          - bench: laravel-6.0
            php: '8.0'
          - bench: laravel-7.0
            php: '7.1'
          - bench: laravel-7.0
            php: '8.0'
          - bench: laravel-8.0
            php: '7.1'
          - bench: laravel-8.0
            php: '7.2'
          - bench: lumen-5.8
            php: '8.0'
          - bench: lumen-6.0
            php: '7.1'
          - bench: lumen-7.0
            php: '7.1'
          - bench: lumen-6.0
            php: '8.0'
          - bench: lumen-7.0
            php: '8.0'
          - bench: lumen-8.0
            php: '7.1'
          - bench: lumen-8.0
            php: '7.2'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - name: Install composer dependencies
        run: composer install
      - name: Install Hydra bench
        run: vendor/bin/hydra install --only=${{ matrix.bench }} -v
      - name: Test with PHPUnit
        run: |
          mkdir coverage
          vendor/bin/phpunit --testdox --coverage-text --coverage-clover=coverage/coverage.xml
        env:
          HYDRA_BENCH: ${{ matrix.bench }}
      - uses: codecov/codecov-action@v1
        if: matrix.bench == 'laravel-8.0' && matrix.php == '8.0'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage.xml
          verbose: true
